# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  159.65.225.255:
    site_hosts:
      - canonical: demo.com
        redirects:
          - www.demo.com
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: info@alexdev.gr
    multisite:
      enabled: true
      subdomains: false 
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
    env:
      domain_current_site: demo.com
